### ISSUE TITLE
error on container run "exec format error"

### ISSUE THREAD

**Issue by jgresham** [optimism-java/hildr#142]
Run command:
```
podman run -d --name hildr-1711574776203 \
-v "/home/ubu/.config/NiceNode/nodes/hildr-1711574776":/data:z -p 8549:8549  \
ghcr.io/optimism-java/hildr:latest-native  --sync-mode full --jwt-file /data/jwtsecret \
--l1-rpc-url http://10.1.70.61:8545/ --l1-ws-rpc-url http://10.1.70.61:8546/ \
--l1-beacon-url http://10.1.70.61:5052/ --l2-rpc-url http://host.containers.internal:8547/ \ 
--l2-engine-url http://host.containers.internal:8553/ --rpc-port 8549 --network optimism
```

error: {"msg":"exec container process `/usr/local/bin/hildr-node`: Exec format error","level":"error","time":"2024-03-27T21:30:15.845010Z"}

**Comment by thinkAfCod** [comment]
ghcr.io/optimism-java/hildr:latest-native image execution platform architecture only supports linux/amd64. I think it may be that the platform architecture does not match.

**Comment by thinkAfCod** [comment]
On a linux/amd64 architecture server, I tested running with Docker and it ran normally.

**Comment by jgresham** [comment]
Ah yes, I was testing on an `arm64` board. noted

**Comment by GrapeBaBa** [comment]
> Ah yes, I was testing on an `arm64` board. noted

Indeed a bug in native image, i just published v0.3.3, you can retry once the new image generated.

**Comment by jgresham** [comment]
Just tried. Seems like same `{"msg":"exec container process `/usr/local/bin/hildr-node`: Exec format error","level":"error","time":"2024-03-28T23:48:48.314113Z"}`

**Comment by GrapeBaBa** [comment]
> Just tried. Seems like same `{"msg":"exec container process `/usr/local/bin/hildr-node`: Exec format error","level":"error","time":"2024-03-28T23:48:48.314113Z"}`

@thinkAfCod Can you help to check?

**Comment by thinkAfCod** [comment]
I may not be able to reproduce the issue you encountered. Could you provide more environment information?

This is the result of running `uname -a` on my server:
```
Linux VM-0-4-ubuntu 5.15.0-86-generic #96-Ubuntu SMP Wed Sep 20 08:23:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

Then,I tried to start using Podman on the server. Here is podman version:
```
ubuntu@VM-0-4-ubuntu:~$ podman version
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.18.1
Built:        Thu Jan  1 08:00:00 1970
OS/Arch:      linux/amd64
```

And Here is my startup command:
```
podman run --rm --name hildr -p 8549:8549  ghcr.io/optimism-java/hildr:v0.3.3-native  --sync-mode full \
--jwt-secret bf549f5188556ce0951048ef467ec93067bc4ea21acebe46ef675cd4e8e015ff \
--l1-rpc-url https://eth-sepolia.g.alchemy.com/v2/<token_id> \
--l1-ws-rpc-url wss://eth-sepolia.g.alchemy.com/v2/<token_id> \
--l1-beacon-url https://few-sleek-sound.ethereum-sepolia.quiknode.pro/<token_id> \
--l2-rpc-url http://10.224.0.4:8545 --l2-engine-url http://10.224.0.4:8551 \
--rpc-port 8549 --network optimism-sepolia
```
After that, it started running immediately.

At the same time, I ran the image using Podman on my own Mac.

This is the result of running uname -a on my Mac:
```
Darwin MacBook-Pro 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000 arm64
```

Podman version info on my Mac:
```
Client:       Podman Engine
Version:      5.0.0
API Version:  5.0.0
Go Version:   go1.22.1
Git Commit:   e71ec6f1d94d2d97fb3afe08aae0d8adaf8bddf0
Built:        Tue Mar 19 17:47:46 2024
OS/Arch:      darwin/arm64

Server:       Podman Engine
Version:      5.0.0-dev-8a643c243
API Version:  5.0.0-dev-8a643c243
Go Version:   go1.21.8
Built:        Mon Mar 18 08:00:00 2024
OS/Arch:      linux/arm64
```

On the Mac, if executed directly, it will prompt to initialize the virtual machine and provide corresponding instructions. Follow the instructions provided to initialize the virtual machine:
```
podman machine init
podman machine start
```
Then start the container with the additional --platform linux/amd64 parameter compared to on the server:
```
podman run --platform linux/amd64 --rm --name hildr -p 8549:8549  ghcr.io/optimism-java/hildr:v0.3.3-native \
--sync-mode full --jwt-secret bf549f5188556ce0951048ef467ec93067bc4ea21acebe46ef675cd4e8e015ff \
--l1-rpc-url https://eth-sepolia.g.alchemy.com/v2/<token_id> \
--l1-ws-rpc-url wss://eth-sepolia.g.alchemy.com/v2/<token_id> \
--l1-beacon-url https://few-sleek-sound.ethereum-sepolia.quiknode.pro/<token_id> \
--l2-rpc-url http://192.168.50.223:8545 --l2-engine-url http://192.168.50.223:8551 --rpc-port 8549 \
--network optimism-sepolia
```
What surprised me is that it could actually start normally.

Because on a Mac, even with the --platform linux/amd64 parameter added, Docker still prompts an error:
```
The current machine does not support all of the following CPU features that are required by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA].
Please rebuild the executable with an appropriate setting of the -march option.
```

**Comment by thinkAfCod** [comment]
On the Mac, when I shut down the virtual machine and remove the --platform linux/amd64 parameter, the startup will display the following error message, but it does not prompt the expected exec Format error message:
```
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
```

**Comment by jgresham** [comment]
sorry, wasn't using a proper archival rpc for l1 🤕
