### ISSUE TITLE
Missing basic flags - `rpc-addr` + `sequencer-private-key`

### ISSUE THREAD

**Issue by barnabasbusa** [optimism-java/hildr#172]
Certain basic flags seems to be missing:

In order to specify which ip address a docker container should be run on, rpc address should be configurable.
`--rpc-addr=0.0.0.0`

Unable to set sequencer private key. 
I have found `--sequencer-enabled` flag, but can't seem to find a flag that will set the private key for the sequencer duties.

**Comment by GrapeBaBa** [comment]
@barnabasbusa `rpc-addr` already fixed, could you check again?

**Comment by GrapeBaBa** [comment]
> It seems like the service now comes online: flags used:
> 
> ```
>             "Cmd": [
>                 "--devnet",
>                 "--jwt-file=/jwt/jwtsecret",
>                 "--l1-beacon-url=http://172.16.0.11:4000",
>                 "--l1-rpc-url=http://172.16.0.9:8545",
>                 "--l1-ws-rpc-url=ws://172.16.0.9:8546",
>                 "--l2-engine-url=http://172.16.0.25:8551",
>                 "--l2-rpc-url=http://172.16.0.25:8545",
>                 "--rpc-addr=0.0.0.0",
>                 "--rpc-port=8547",
>                 "--sync-mode=full",
>                 "--network=/network-configs/rollup.json",
>                 "--disc-boot-nodes=enr:-J-4QEfuoT7WWHQ_wN5DMlDms0U8y3jxFciO3tb9TTObIJ20YrwQROvgn5cs6sbr0ibkZch-EtxbFPu88RB97LcfatWGAZCX46qsgmlkgnY0gmlwhKwQABiHb3BzdGFja4Xkq4MBAIlzZWNwMjU2azGhAjyWt3z1Kw7_FtzbtBxq4Ru7OVxrKBmnW76ZmYLIiRN6g3RjcIIjK4N1ZHCCIys"
>             ],
> ```
> 
> I see a huge amount of DEBUG logs with:
> 
> ```
> 14:00:19.368 [] DEBUG i.o.utilities.rpc.HttpClientProvider trace_id=25e4c3f8092af3a6cc4cc869ac1f9d95 span_id=98265200f022d2e6 trace_flags=01 <-- END HTTP (34ms, 1721-byte body)
> 14:00:19.369 [InnerWatcher] DEBUG io.optimism.l1.InnerWatcher trace_id=48f608a872acf1429339c51ab408d754 span_id=91539d14e61539cd trace_flags=01 will update system config with newest log: currentBlock(10) <= headBlock(44)
> 14:00:19.369 [InnerWatcher] DEBUG io.optimism.l1.InnerWatcher trace_id=48f608a872acf1429339c51ab408d754 span_id=91539d14e61539cd trace_flags=01 will poll block: 0xa
> 14:00:19.370 [] DEBUG i.o.utilities.rpc.HttpClientProvider trace_id=65a20d91192a8d6d8123a5d83c3a843a span_id=229aa993343ef926 trace_flags=01 --> POST http://172.16.0.9:8545/
> 14:00:19.370 [] DEBUG i.o.utilities.rpc.HttpClientProvider trace_id=65a20d91192a8d6d8123a5d83c3a843a span_id=229aa993343ef926 trace_flags=01 Content-Type: application/json; charset=utf-8
> 14:00:19.370 [] DEBUG i.o.utilities.rpc.HttpClientProvider trace_id=65a20d91192a8d6d8123a5d83c3a843a span_id=229aa993343ef926 trace_flags=01 Content-Length: 79
> 14:00:19.370 [] DEBUG i.o.utilities.rpc.HttpClientProvider trace_id=65a20d91192a8d6d8123a5d83c3a843a span_id=229aa993343ef926 trace_flags=01
> 14:00:19.370 [] DEBUG i.o.utilities.rpc.HttpClientProvider trace_id=65a20d91192a8d6d8123a5d83c3a843a span_id=229aa993343ef926 trace_flags=01 {"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0xa",true],"id":30}
> 14:00:19.370 [] DEBUG i.o.utilities.rpc.HttpClientProvider trace_id=65a20d91192a8d6d8123a5d83c3a843a span_id=229aa993343ef926 trace_flags=01 --> END POST (79-byte body)
> 14:00:19.370 [] WARN  i.o.u.rpc.RetryRateLimitInterceptor trace_id=65a20d91192a8d6d8123a5d83c3a843a span_id=229aa993343ef926 trace_flags=01 there has reached rate limit, but will retry again later
> 14:00:19.395 [] DEBUG i.o.utilities.rpc.HttpClientProvider trace_id=65a20d91192a8d6d8123a5d83c3a843a span_id=229aa993343ef926 trace_flags=01 <-- 200 OK http://172.16.0.9:8545/ (24ms)
> 14:00:19.396 [] DEBUG i.o.utilities.rpc.HttpClientProvider trace_id=65a20d91192a8d6d8123a5d83c3a843a span_id=229aa993343ef926 trace_flags=01 Content-Type: application/json
> 14:00:19.396 [] DEBUG i.o.utilities.rpc.HttpClientProvider trace_id=65a20d91192a8d6d8123a5d83c3a843a span_id=229aa993343ef926 trace_flags=01 Vary: Origin
> 14:00:19.396 [] DEBUG i.o.utilities.rpc.HttpClientProvider trace_id=65a20d91192a8d6d8123a5d83c3a843a span_id=229aa993343ef926 trace_flags=01 Date: Tue, 09 Jul 2024 14:00:19 GMT
> 14:00:19.396 [] DEBUG i.o.utilities.rpc.HttpClientProvider trace_id=65a20d91192a8d6d8123a5d83c3a843a span_id=229aa993343ef926 trace_flags=01
> 14:00:19.396 [] DEBUG i.o.utilities.rpc.HttpClientProvider trace_id=65a20d91192a8d6d8123a5d83c3a843a span_id=229aa993343ef926 trace_flags=01 {"jsonrpc":"2.0","id":30,"result":{"baseFeePerGas":"0xfaf2d5f","blobGasUsed":"0x0","difficulty":"0x0","excessBlobGas":"0x0","extraData":"0xd883010e07846765746888676f312e32322e35856c696e7578","gasLimit":"0x1813611","gasUsed":"0x0","hash":"0x8e5045c4245c213fe9178c4cc8a735103470b5ed7ec03466d971af89217fbf0a","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","miner":"0x8943545177806ed17b9f23f0a21ee5948ecaa776","mixHash":"0xed3287c586a3db68d1465a549a3da2081a810bed2be71b246a87951eedbe2bb2","nonce":"0x0000000000000000","number":"0xa","parentBeaconBlockRoot":"0x674731c9da514d9c82f04c05cd0482f5c7fe0cd0de9023998c5f6e99fc1e9bd4","parentHash":"0x7de69a398aaf12c649dc636324a6ca51f9a0e74f64965a9fc3b7a78334992bdf","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","size":"0x260","stateRoot":"0x555970cb73bd6c6f9f7a1a6fd12806e2c4c02d484d2f126afe1fd58043e2abbd","timestamp":"0x668d41a1","totalDifficulty":"0x1","transactions":[],"transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","uncles":[],"withdrawals":[],"withdrawalsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421"}}
> ```
> 
> EL doesn't seem to see any blocks.
> 
> Reproducable with this one liner:
> 
> `kurtosis run github.com/ethpandaops/optimism-package@bbusa/hildr --args-file https://raw.githubusercontent.com/ethpandaops/optimism-package/ac4abcd05d189603e34fa60e0adc3a519d4235cc/.github/tests/hildr.yaml`

Let us check.

**Comment by GrapeBaBa** [comment]
> It seems like the service now comes online: flags used:
> 
> ```
>             "Cmd": [
>                 "--devnet",
>                 "--jwt-file=/jwt/jwtsecret",
>                 "--l1-beacon-url=http://172.16.0.11:4000",
>                 "--l1-rpc-url=http://172.16.0.9:8545",
>                 "--l1-ws-rpc-url=ws://172.16.0.9:8546",
>                 "--l2-engine-url=http://172.16.0.25:8551",
>                 "--l2-rpc-url=http://172.16.0.25:8545",
>                 "--rpc-addr=0.0.0.0",
>                 "--rpc-port=8547",
>                 "--sync-mode=full",
>                 "--network=/network-configs/rollup.json",
>                 "--disc-boot-nodes=enr:-J-4QEfuoT7WWHQ_wN5DMlDms0U8y3jxFciO3tb9TTObIJ20YrwQROvgn5cs6sbr0ibkZch-EtxbFPu88RB97LcfatWGAZCX46qsgmlkgnY0gmlwhKwQABiHb3BzdGFja4Xkq4MBAIlzZWNwMjU2azGhAjyWt3z1Kw7_FtzbtBxq4Ru7OVxrKBmnW76ZmYLIiRN6g3RjcIIjK4N1ZHCCIys"
>             ],
> ```
> 
> I see a huge amount of DEBUG logs with:
> 
> ```
> 14:00:19.368 [] DEBUG i.o.utilities.rpc.HttpClientProvider trace_id=25e4c3f8092af3a6cc4cc869ac1f9d95 span_id=98265200f022d2e6 trace_flags=01 <-- END HTTP (34ms, 1721-byte body)
> 14:00:19.369 [InnerWatcher] DEBUG io.optimism.l1.InnerWatcher trace_id=48f608a872acf1429339c51ab408d754 span_id=91539d14e61539cd trace_flags=01 will update system config with newest log: currentBlock(10) <= headBlock(44)
> 14:00:19.369 [InnerWatcher] DEBUG io.optimism.l1.InnerWatcher trace_id=48f608a872acf1429339c51ab408d754 span_id=91539d14e61539cd trace_flags=01 will poll block: 0xa
> 14:00:19.370 [] DEBUG i.o.utilities.rpc.HttpClientProvider trace_id=65a20d91192a8d6d8123a5d83c3a843a span_id=229aa993343ef926 trace_flags=01 --> POST http://172.16.0.9:8545/
> 14:00:19.370 [] DEBUG i.o.utilities.rpc.HttpClientProvider trace_id=65a20d91192a8d6d8123a5d83c3a843a span_id=229aa993343ef926 trace_flags=01 Content-Type: application/json; charset=utf-8
> 14:00:19.370 [] DEBUG i.o.utilities.rpc.HttpClientProvider trace_id=65a20d91192a8d6d8123a5d83c3a843a span_id=229aa993343ef926 trace_flags=01 Content-Length: 79
> 14:00:19.370 [] DEBUG i.o.utilities.rpc.HttpClientProvider trace_id=65a20d91192a8d6d8123a5d83c3a843a span_id=229aa993343ef926 trace_flags=01
> 14:00:19.370 [] DEBUG i.o.utilities.rpc.HttpClientProvider trace_id=65a20d91192a8d6d8123a5d83c3a843a span_id=229aa993343ef926 trace_flags=01 {"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0xa",true],"id":30}
> 14:00:19.370 [] DEBUG i.o.utilities.rpc.HttpClientProvider trace_id=65a20d91192a8d6d8123a5d83c3a843a span_id=229aa993343ef926 trace_flags=01 --> END POST (79-byte body)
> 14:00:19.370 [] WARN  i.o.u.rpc.RetryRateLimitInterceptor trace_id=65a20d91192a8d6d8123a5d83c3a843a span_id=229aa993343ef926 trace_flags=01 there has reached rate limit, but will retry again later
> 14:00:19.395 [] DEBUG i.o.utilities.rpc.HttpClientProvider trace_id=65a20d91192a8d6d8123a5d83c3a843a span_id=229aa993343ef926 trace_flags=01 <-- 200 OK http://172.16.0.9:8545/ (24ms)
> 14:00:19.396 [] DEBUG i.o.utilities.rpc.HttpClientProvider trace_id=65a20d91192a8d6d8123a5d83c3a843a span_id=229aa993343ef926 trace_flags=01 Content-Type: application/json
> 14:00:19.396 [] DEBUG i.o.utilities.rpc.HttpClientProvider trace_id=65a20d91192a8d6d8123a5d83c3a843a span_id=229aa993343ef926 trace_flags=01 Vary: Origin
> 14:00:19.396 [] DEBUG i.o.utilities.rpc.HttpClientProvider trace_id=65a20d91192a8d6d8123a5d83c3a843a span_id=229aa993343ef926 trace_flags=01 Date: Tue, 09 Jul 2024 14:00:19 GMT
> 14:00:19.396 [] DEBUG i.o.utilities.rpc.HttpClientProvider trace_id=65a20d91192a8d6d8123a5d83c3a843a span_id=229aa993343ef926 trace_flags=01
> 14:00:19.396 [] DEBUG i.o.utilities.rpc.HttpClientProvider trace_id=65a20d91192a8d6d8123a5d83c3a843a span_id=229aa993343ef926 trace_flags=01 {"jsonrpc":"2.0","id":30,"result":{"baseFeePerGas":"0xfaf2d5f","blobGasUsed":"0x0","difficulty":"0x0","excessBlobGas":"0x0","extraData":"0xd883010e07846765746888676f312e32322e35856c696e7578","gasLimit":"0x1813611","gasUsed":"0x0","hash":"0x8e5045c4245c213fe9178c4cc8a735103470b5ed7ec03466d971af89217fbf0a","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","miner":"0x8943545177806ed17b9f23f0a21ee5948ecaa776","mixHash":"0xed3287c586a3db68d1465a549a3da2081a810bed2be71b246a87951eedbe2bb2","nonce":"0x0000000000000000","number":"0xa","parentBeaconBlockRoot":"0x674731c9da514d9c82f04c05cd0482f5c7fe0cd0de9023998c5f6e99fc1e9bd4","parentHash":"0x7de69a398aaf12c649dc636324a6ca51f9a0e74f64965a9fc3b7a78334992bdf","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","size":"0x260","stateRoot":"0x555970cb73bd6c6f9f7a1a6fd12806e2c4c02d484d2f126afe1fd58043e2abbd","timestamp":"0x668d41a1","totalDifficulty":"0x1","transactions":[],"transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","uncles":[],"withdrawals":[],"withdrawalsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421"}}
> ```
> 
> EL doesn't seem to see any blocks.
> 
> Reproducable with this one liner:
> 
> `kurtosis run github.com/ethpandaops/optimism-package@bbusa/hildr --args-file https://raw.githubusercontent.com/ethpandaops/optimism-package/ac4abcd05d189603e34fa60e0adc3a519d4235cc/.github/tests/hildr.yaml`

@barnabasbusa fixed a devnet issue in v0.4.4, please check again.
